import Head from 'next/head'
import Header from '../layout/header';
import Homebanner from '../components/home/homebanner';
import WhoWeAre from '../components/home/whoWeAre';
import Scrollparallex from '../components/home/scrollparallex';


export default function Home({children}) {
  return (
    <div>
      <Head>
        <title>Business Moglix App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/img/favicon.png" />
        <link rel="stylesheet=" href='/node_modules/accordion-slider/dist/css/jquery.accordionSlider.min.css' />
        <link rel="stylesheet=" href='/node_modules/accordion-slider/dist/js/jquery.accordionSlider.js' />
      </Head>
     <div className='bm_pagewrapper'>
       <main>
        <section className='w-100'>
            <Homebanner />
            <WhoWeAre />   
            {/* {props.children} */}
            <Scrollparallex /> 
            
            
                   
        </section>
       </main>
      </div>
       
    </div>
  )
}
